# Hexo Configuration Example
# Copy this to _config.yml and update with your values

# Site
title: Your Blog Title
subtitle: Your Subtitle
description: "Your blog description"
keywords: ["keyword1", "keyword2"]
author: Your Name
language: en
timezone: "UTC"

# URL
url: https://yourdomain.com
permalink: :year/:month/:day/:title/
pretty_urls:
  trailing_index: false
  trailing_html: false

# Directory
source_dir: source
public_dir: public
tag_dir: blog/tags
archive_dir: archive
category_dir: blog/categories

# Writing
default_layout: post
external_link:
  enable: true
  field: site
render_drafts: false
highlight:
  enable: true
  line_number: true
feed:
  enable: true
  type: rss2
  path: rss2.xml

# Home page and sections
index_generator:
  path: ''
  per_page: 20  # IMPORTANT: Set to a reasonable number to avoid huge HTML files
  order_by: -date

# Metadata
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: "mtime"

# Pagination
per_page: 20  # IMPORTANT: Don't use 0 (unlimited)
pagination_dir: page

# Extensions
theme: san-diego

# NOTE: Admin configuration should be stored in environment variables
# Do NOT add admin credentials to this file

# Deployment - Using GitHub Actions instead of git deployment
# deploy:
#   type: git
#   repo: git@github.com:username/username.github.io.git
#   branch: main

ejs:
  async: true

# Asset handling
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
  lazyLoad: false

# Post types
post_types:
  link:
    icon: 📎
    class: link-share
    header_style: alert
    url_field: true
  project_gallery:
    icon: 🎨
    class: project-gallery
    header_style: full-width

# Performance Optimizations
minify:
  enable: true
  preview: false
  exclude: ['*.min.*']
  js:
    enable: true
    sourceMap:
      enable: false
      sourceMappingURL: false
    options: {}
  css:
    enable: true
    sourceMap:
      enable: false
      sourceMappingURL: false
    options: {}
  html:
    enable: true
    options:
      minifyJS: true
      minifyCSS: true
      removeComments: true
      collapseWhitespace: true
      removeAttributeQuotes: true
  image:
    enable: true
    options: {}

# Lazy Load Images
lazyload:
  enable: false  # Theme uses native loading="lazy"
  loadingImg: 
  placeholder: data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvc3ZnIj48Y2lyY2xlIGN4PSI1MCIgY3k9IjUwIiByPSI0MCIgZmlsbD0iI2VlZSIvPjwvc3ZnPg==

# Sitemap
sitemap:
  path: sitemap.xml
  rel: false
  tags: true
  categories: true

# Search
search:
  path: search.xml
  field: post
  content: true

# Portfolio Company Configuration
portfolio:
  companies:
    order:
      - 'Company 1'
      - 'Company 2'
      - 'Company 3'
    years:
      'Company 1': '2020—Present'
      'Company 2': '2018—2020'
      'Company 3': '2016—2018'