# Hexo Configuration

# Site
title: Thomas Walichiewicz
subtitle: Designer | Developer | Thinker
description: "Thomas Walichiewicz - Designer, Developer, Thinker"
keywords: ["design", "portfolio", "blog", "developer"]
author: Thomas Walichiewicz
language: en
timezone: "America/Los_Angeles"

# URL
url: https://twalichiewicz.github.io  # Ensure this is correct
permalink: :year/:month/:day/:title/
pretty_urls:
  trailing_index: false
  trailing_html: false

# Directory
source_dir: source
public_dir: public
tag_dir: blog/tags
archive_dir: archive
category_dir: blog/categories

# Writing
default_layout: post
external_link:
  enable: true
  field: site
render_drafts: false
highlight:
  enable: true
  line_number: true
feed:
  enable: true
  type: rss2
  path: rss2.xml

# Home page and sections
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Metadata
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: "mtime"

# Pagination
per_page: 10
pagination_dir: page

# Extensions
theme: san-diego  # Ensure this matches the theme directory name
admin:
  username: twalichiewicz
  password_hash: $2a$10$7vYp2Wx1h3bf8LuNGTbSb.Zavzfp1xVThMXOnZuG9yIPCGCUtHkcq  # Ensure this is correct
  secret: secret-key  # Ensure this is correct

# Deployment
deploy:
  type: git
  repo: git@github.com:twalichiewicz/website.git  # Ensure this is correct
  branch: main  # Ensure this is correct

ejs:
  async: true

# Asset handling
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
  lazyLoad: true

# Post types
post_types:
  link:
    icon: 📎
    class: link-share
    header_style: alert
    url_field: true  # Enable URL field handling
  project_gallery:
    icon: 🎨
    class: project-gallery
    header_style: full-width
