# Hexo Configuration

# Site
title: Thomas Walichiewicz
subtitle: Designer | Developer | Thinker
description: "Thomas Walichiewicz - Designer, Developer, Thinker"
keywords: ["design", "portfolio", "blog", "developer"]
author: Thomas Walichiewicz
language: en
timezone: "UTC"

# URL
url: https://twalichiewicz.github.io  # Ensure this is correct
permalink: :year/:month/:day/:title/
pretty_urls:
  trailing_index: false
  trailing_html: false

# Directory
source_dir: source
public_dir: public
tag_dir: blog/tags
archive_dir: archive
category_dir: blog/categories

# Writing
default_layout: post
external_link:
  enable: true
  field: site
render_drafts: false
highlight:
  enable: true
  line_number: true
feed:
  enable: true
  type: rss2
  path: rss2.xml

# Home page and sections
index_generator:
  path: ''
  per_page: 0
  order_by: -date

# Metadata
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: "mtime"

# Pagination
per_page: 0
pagination_dir: page

# Extensions
theme: san-diego  # Ensure this matches the theme directory name
# Admin configuration removed - store in environment variables instead

# Deployment - Using GitHub Actions instead of git deployment
# deploy:
#   type: git
#   repo: git@github.com:twalichiewicz/twalichiewicz.github.io.git
#   branch: main

ejs:
  async: true

# Asset handling
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
  lazyLoad: false

# Post types
post_types:
  link:
    icon: 📎
    class: link-share
    header_style: alert
    url_field: true  # Enable URL field handling
  project_gallery:
    icon: 🎨
    class: project-gallery
    header_style: full-width

# Performance Optimizations
# Hexo-minify - Minify HTML, CSS, JS and optimize images  
minify:
  enable: true # Re-enable hexo-minify
  preview: false # Whether to compress during local preview
  exclude: ['*.min.*']
  js:
    enable: true
    sourceMap:
      enable: false # generate sourceMap
      sourceMappingURL: false # //# sourceMappingURL=xxx.js.map
    options: {}
  css:
    enable: true
    sourceMap: # Added to explicitly disable if it was an implicit option
      enable: false
      sourceMappingURL: false
    options: {}
  html:
    enable: true
    options:
      minifyJS: true # Compressed JavaScript
      minifyCSS: true # CSS Compressed
      removeComments: true # Remove the comments
      collapseWhitespace: true # Delete any extra space
      removeAttributeQuotes: true # Delete attribute quotes
  image:
    enable: false # Disabled - using separate Sharp.js optimization script instead
    options: {}

# Lazy Load Images
lazyload:
  enable: false # Disable hexo-lazyload-image as theme uses native loading="lazy"
  loadingImg: # Loading image placeholder
  placeholder: data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvc3ZnIj48Y2lyY2xlIGN4PSI1MCIgY3k9IjUwIiByPSI0MCIgZmlsbD0iI2VlZSIvPjwvc3ZnPg==

# Sitemap
sitemap:
  path: sitemap.xml
  rel: false
  tags: true
  categories: true

# Search
search:
  path: search.xml
  field: post
  content: true

# Portfolio Company Configuration
portfolio:
  companies:
    order:
      - 'Autodesk'
      - 'Human Interest'
      - 'Common Cents Lab'
      - 'Lyra Health'
      - 'Maisha Meds'
      - 'Other Projects'
    years:
      'Autodesk': '2019—Present'
      'Human Interest': '2017—2019'
      'Common Cents Lab': '2016—2017'
      'Lyra Health': '2015'
      'Maisha Meds': '2013-2014'
